# Generated by Django 4.1.5 on 2023-02-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.AutoField(primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(max_length=50)),
                ('tffrs_link_for_athlete', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Record',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr', models.CharField(max_length=50)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prs.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prs.event')),
            ],
        ),
    ]
