# Generated by Django 4.1.7 on 2023-07-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.AutoField(primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(max_length=50)),
                ('athlete_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=50)),
                ('college_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Record',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr', models.CharField(max_length=50)),
                ('pr_link', models.CharField(max_length=100)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prs.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prs.event')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prs.college'),
        ),
    ]
