# Generated by Django 4.1.5 on 2023-01-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.AutoField(primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(max_length=50)),
                ('athlete_gender_male', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Record',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('time', models.TimeField(null=True)),
                ('tffrs_link', models.CharField(max_length=100)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prs.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prs.event')),
            ],
        ),
    ]
