# Generated by Django 4.1.5 on 2023-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_record',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='personal_record',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
